### PR TITLE
Non-unicode primitive support and major Kanji database update

### PR DESCRIPTION
**Pull request by mjuhanne**
#### Add capability to use primitives that have no Unicode character representation. They are instead referenced with [primitive_name] tags in primitives and primitive_of lists as well as Heisig stories and comments.
The tags are then converted into image links when constructing their visual representation.

- Included are .svg files for the non-Unicode primitives gathered from https://github.com/cyphar/heisig-rtk-index repository. I have included also few extra ones that the repository was missing.

#### Major update to kanji.db, trying to replicate Heisig's keywords and primitives as accurately as possible:
- Add all the missing non-Unicode character primitives
- Fix many mix-ups between primitives ('good luck' vs 'lidded crock',  'chop-seal' vs 'stamps' among others)
- separate 'hand' and 'fingers' primitives for clarity.
- primitives for 'flowers', 'city walls' and 'pinnacle' actually reference the more common radicals instead of weird archaic ones
- Fix many erroneous primitive references (such as 'water' being used instead of 'rice grains')
- Fix many Heisig stories and comments. Also add italic and bold text when referencing keywords

Changes to the original kanji database (as of 7/2023) are merged from kanji-ext.tsv files.  Included is the updated kanji.db. There are three different batches of updates present in this PR.  Log of changes can be found in corresponding db_merge_log_X.md files in Markdown format (the log and tsv files are now removed for cleaner addon directory, but can be found in the individual commits below if needed)

### CODE REVIEW

**Comment by calculuschild** [comment]
See https://github.com/migaku-official/Migaku-Kanji-Addon/issues/175 where I have done some simple testing.

**Comment by calculuschild** [comment]
Just downloaded the latest changes you made. A few notes I've been collecting on entries that still seem to need fixing:

1) 邑 (city walls?)- Has no primitives or name listed, though they are mentioned in the stories.
2) 求 (request) - Primitives seem to be missing according to RTK (should be "arrowhead, drop, rice"). But one story points out this should be "water" instead "rice"
3) 捕 (catch) - Also should use the "arrowhead" primitive instead of "arrow" 
4) 奐 (clear, bright) - Missing all information
5) 巛 (flood) - Completely blank. Other cards like 拶 (imminent) now incorrectly point to the primitive 川 (stream) which doesn't match the stories

It's possible some of these are leftover garbage cards after rebuilding the deck, but just in case.

**Comment by mjuhanne** [comment]
@calculuschild  Thank you for testing!

> Just downloaded the latest changes you made. A few notes I've been collecting on entries that still seem to need fixing:
> 
> 1. 邑 (city walls?)- Has no primitives or name listed, though they are mentioned in the stories.
Corrected

> 2. 求 (request) - Primitives seem to be missing according to RTK (should be "arrowhead, drop, rice"). But one story points out this should be "water" instead "rice"

Corrected
> 3. 捕 (catch) - Also should use the "arrowhead" primitive instead of "arrow"

I think there's some confusion what Heisig actually means with the 'arrowhead'. It's not listed as a separate primitive but mentioned in the comments of 'arrow', 'request' and 'dog tag' primitives. How I see it, the arrow is still there in those primitives but the body is straightened out and  merged with other primitives (like what happens in many of the kanjis in his stories). That's why I haven't created a yet another sub-primitive but keep referring to the 'arrow'.

> 4. 奐 (clear, bright) - Missing all information

That's a non-Heisig primitive (shared by 換 and 喚), but will be listed as an secondary/alternate new primitive after the next patch of update.  There will be later a possibility to learn with these advanced (non-Heisig) primitives (optional feature). 

Also I'm adding a feature for the user to modify the primitive list of each kanji (as well as the Heisig story and comments) to facilitate a crowdsourcing effort to go thru all the kanjis that is not included in Heisig's books. I'm now in the middle of cross checking database with RTK3 but for the rarer stuff (kanji frequency 3000+ to ~12000) I obviously don't have time to do myself. I'm not a paid worker of Migaku project, but just a volunteer doing this stuff on my free time :)

> 5. 巛 (flood) - Completely blank. Other cards like 拶 (imminent) now incorrectly point to the primitive 川 (stream) which doesn't match the stories

 巛 is now listed as an alternative to 川 and database should reflect all the changes now.

> 
> It's possible some of these are leftover garbage cards after rebuilding the deck that I just need to suspend, but reporting just in case.

**Comment by mjuhanne** [comment]
Closing for now. I'll make a new PR that uses the new refactored code (in other PR) and clean this up a bit too.

**Pull request closed without merging**
