### PR TITLE
Refactor HTML files: Separate common JavaScript and HTML sections into separate files

### PR DESCRIPTION
**Pull request by mjuhanne**
Easier maintenance of HTML files (no more 8000+ line front/back-production/recognition.html or lookup.html)

### CODE REVIEW

**Comment by hgiesel** [comment]
First of all, thanks for you PR.
Getting rid of more than 10k lines of code sounds really good 🙈
I will review this PR shortly

**Comment by MinmoTech** [comment]
Yeah actually I'm curious @mjuhanne, how were you able to get rid of so much code? :eyes:

**Comment by mjuhanne** [comment]
@MinmoTech The biggest culprit was the Raphael SVG drawing code (6400 lines), which was identical in lookup.html and back_production/recognition.html.  Then the same thing for Draw me A kanji code, a front end for Raphael (800 lines), japanese-util.js (300 lines). Most of the HTML code is also identical and could be shared between HTML files.

**Comment by mjuhanne** [comment]
> First of all, thanks for you PR. Getting rid of more than 10k lines of code sounds really good 🙈 I will review this PR shortly
> 
> A question: when merging, which order would you suggest for your PRs, so it causes the least trouble for you in terms of conflicts, etc.?

Thank you for the prompt reply. Either new PR first is fine, I will still have to modify the original PR to use these new refactorings and clean it up a bit, so I will cancel it for now and make a new one shortly

**Review by MinmoTech — APPROVED** [review]

**Comment by hgiesel** [comment]
LGTM!

**Pull request merged**
