### PR TITLE
Filter out suspended cards when looking ahead

### LINKED ISSUE #147: [BUG] Learn ahead kanji are added for suspended cards
**Describe the bug**
When using the learn ahead kanji feature, I got kanji cards created for sentence cards that are suspended.

**To Reproduce**
1. Set up a deck for learn-ahead cards
2. Exit settings
3. Cards get created regardless of cards being suspended or not

**Expected behavior**
My expectation is that suspended cards are ignored.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Anki Version 2.1.49

### PR DESCRIPTION
**Pull request by BenjaminPrice**
Quick fix for filtering out the suspended cards
Resolved #147

### CODE REVIEW

**Comment by fw42** [comment]
I personally actually prefer the old behaviour. Any chance to make it configurable instead of always ignoring suspended cards?

**Comment by RicBent** [comment]
Why exactly would you want "learn ahead" suspended cards if they won't appear in your reviews?

**Comment by fw42** [comment]
FWIW I'm using this together with another add-on that suspends all cards that contain Kanji that haven't matured yet. I find this to be a really nice workflow and it prevents me from accidentally learning cards with Kanji that I'm not familiar enough with yet (or that are still stuck in the backlog of the recognition deck).

If you think that not enough people would be interested in a configuration option then that's fine with me, I can always go in and manually revert the change just for myself. Just thought I'd ask. Thanks anyway.

**Comment by RicBent** [comment]
Yeah I think I'm merging this for now. I honestly am a bit reluctant to add even more options that would only be used by very few people (look at it, it's already a mess).

Potentially we can add features that would integrate the functionality of that addon. Something like "suspend card until all kanji learned"?

**Comment by saxoncameron** [comment]
> FWIW I'm using this together with another add-on that suspends all cards that contain Kanji that haven't matured yet. I find this to be a really nice workflow and it prevents me from accidentally learning cards with Kanji that I'm not familiar enough with yet (or that are still stuck in the backlog of the recognition deck).
> 
> If you think that not enough people would be interested in a configuration option then that's fine with me, I can always go in and manually revert the change just for myself. Just thought I'd ask. Thanks anyway.

Sounds like this use-case is adequately addressed already with the "learn-ahead" feature, imo!

**Pull request merged**
