### PR TITLE
Make Kanji DB operations thread-safe

### PR DESCRIPTION
**Pull request by mjuhanne**

### CODE REVIEW

**Comment by mjuhanne** [comment]
```
# check_same_thread set to false to allow gui thread updating while stuff is updated
        # only one thread ever accesses the db
        self.con = sqlite3.connect(kanji_db_path, check_same_thread=False)
```
The check_same_thread option here doesn't really work, so that's why the locking mechanism is needed.
 [See discussion here](https://stackoverflow.com/questions/22739590/how-to-share-single-sqlite-connection-in-multi-threaded-python-application)

**Review by MinmoTech — APPROVED** [review]

**Comment by hgiesel** [comment]
I haven't encountered any issue with it, but I think the code might benefit from using a [contextmanager](https://docs.python.org/3/library/contextlib.html#contextlib.closing)?

I'm not sure if these db operations can ever error, but in that case they would stay locked.

**Review by hgiesel — CHANGES_REQUESTED** [review]
(see above)

**Comment by mjuhanne** [comment]
@hgiesel 
Ah, you mean like this? 
Instead of:
```
        self.crs_executemany_and_commit(
            "INSERT INTO usr.words (note_id,word,reading,is_new) VALUES (?,?,?,?)",
            [(note_id, w, r, is_new) for (w, r) in words],
        )
```
use rlock context manager facility:
```
 with self.lock:
        self.crs.executemany(
            "INSERT INTO usr.words (note_id,word,reading,is_new) VALUES (?,?,?,?)",
            [(note_id, w, r, is_new) for (w, r) in words],
        )
        self.crs.commit()
```

**Comment by hgiesel** [comment]
Yes, just in case the execution throws, that the lock is properly released again.

Altogether it would probably look something like this:

```python
def use_lock():
    try:
        self.lock.acquire(True)
        yield
    finally:
        self.lock.release()

# and then int the methods itself...
     ....
     with use_lock:
        self.crs.executemany(
            "INSERT INTO usr.words (note_id,word,reading,is_new) VALUES (?,?,?,?)",
            [(note_id, w, r, is_new) for (w, r) in words],
        )
        self.crs.commit()
     ....
```

**Comment by mjuhanne** [comment]
@hgiesel  Thank you for your help. 

Just for clarification, maybe I've misunderstood something, but is the structure described by you necessary? It seems that the 'with' keyword should do the acquire/release procedure automatically when it comes to locking? 
RLock doesn't have locked() function to see the results but with Lock here's a simple test:

```
from threading import Lock

lock = Lock()

print("lock test #1", lock.locked())

with lock:
    print("lock test #1", lock.locked())

print("lock test #1", lock.locked())


try:
    with lock:
        print("lock test #2", lock.locked())
        raise Exception("testing")
except:
    pass

print("lock test #2", lock.locked())
```
prints this:
```
lock test #1 False
lock test #1 True
lock test #1 False
lock test #2 True
lock test #2 False
```

**Comment by hgiesel** [comment]
Yep, you're rigth, it's [documented](https://docs.python.org/3/library/threading.html#using-locks-conditions-and-semaphores-in-the-with-statement). I just didn't know :)

**Comment by hgiesel** [comment]
Thanks a lot for the adjustment :)

**Pull request merged**
